### ISSUE TITLE
Add Testing documentation

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-friends#262]
### Problem description

Сейчас нет тестовой документации, - тест кейсов, чеклистов, списка требований, по которым проект можно тестировать.
Их необходимо добавить.

### Proposed solution

Добавить тестовую документацию в свободном формате (можно YAML) в директории https://github.com/hexlet-rus/runit/tree/main/docs
Потом мы унесем эту документацию куда-нибудь. и будем её улучшать/развивать.

**Comment by Kem0111** [comment]
Беру в работу. Документировать нужно каждый тесткейс в проекте?

**Comment by fey** [comment]
Сейчас у нас нет тестовой докуменатции вообще.
Поэтому можно проработать 
1) сценарии пользования. Можно поспрашивать у ребят (в сообществе телеграма или в маттермосте), что это за проект, как он работает и тд и тп
2) из этого будут сформированы требования
3) из требований тест кейсы, что тестировать.

**Comment by Kem0111** [comment]
Хорошо, а из того что уже протестировано, наверно нужно тоже документацию делать например в таком ключе:
test_cases:
  - test_name: "RegistrationPageViewTest"
    preconditions: "None"
    steps:
      - description: "Send get request"
        action: "client.get(reverse_lazy('auth:registration'))"
      - description: "Check data page assertions"
        action: "_assert_* (various assertions)"
    expected_result: "HTTPStatus.OK and correct forms data"
  - test_name: "SuccessRegistrationTest"
    preconditions: "None"
    steps:
      - description: "Send valid registration request"
        action: "client.post(reverse_lazy('auth:registration'), data={...})"
    expected_result: "Redirect to login page and user created in database"
    
    или сразу приступать к тому что не протестировано?

**Comment by fey** [comment]
А это какой-то фреймворк?)
Просто данная задачка она для ручных тестировщиков. Но вообще если вы умете программировать на Python, есть еще другая задача. У нас используется сервис Allure (Testops), куда мы можем отправлять информацию о автотестах.

Т.е. мы тут разделяем задачку на несколько

1) ручной тестировщик описывает требвоания, тесткейсы, юзкейсы
2) автотестировщик/разработчик - подключюает allure

**Comment by Kem0111** [comment]
Изначально я понял задачу так: 
в директории docs нужно создать 3 файла yml
```
docs/
 │
├── test_cases.yaml
├── checklists.yaml
└── requirements.yaml
```
и сделать документацию на тесты в таком виде
```
test_cases:
  - test_name: "RegistrationPageViewTest"
    description: "Test for validating the common registration page view."
    preconditions: "None"
    steps:
      - description: "Send get request"
        action: "client.get(reverse_lazy('auth:registration'))"
      - description: "Check data page assertions"
        action: "_assert_* (various assertions)"
    expected_result: "HTTPStatus.OK and correct forms data"
  - test_name: "SuccessRegistrationTest"
    description: "Test for checking successful user registration."
    preconditions: "None"
    steps:
      - description: "Send valid registration request"
        action: "client.post(reverse_lazy('auth:registration'), data={...})"
    expected_result: "Redirect to login page and user created in database"
остальные тест-кейсы...

checklists:
  - checklist_name: "Registration Page Tests"
    description: "Checklist for all the tests related to user registration page."
    items:
      - "RegistrationPageViewTest"
      - "SuccessRegistrationTest"
остальные чек-листы...

requirements:
  - requirement_id: "REQ-1"
    requirement_text: "The system should allow user registration"
    related_test_cases: 
      - "RegistrationPageViewTest"
      - "SuccessRegistrationTest"
 остальные требования для тест-рейсов...

```
Мои скилы в тестировании не слишком высокие, я больше разработчик, но разобраться с allure наверно смогу
